from __future__ import annotations

from typing import Protocol


class MfaProvider(Protocol):
    def generate_totp_secret(self) -> str: ...
    def generate_recovery_codes(self) -> list[str]: ...
    def provisioning_uri(self, secret: str, email: str, issuer: str) -> str: ...
    def verify_totp(self, secret: str, code: str) -> bool: ...
