from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol


class RepositoryPorts(Protocol):
    def create_user(self, email: str, password_hash: str, account_type: str = "user") -> Any: ...
    def get_user_by_email(self, email: str) -> Any | None: ...
    def get_user(self, user_id: str) -> Any | None: ...
    def has_site_owner(self) -> bool: ...
    def verify_user(self, user_id: str) -> None: ...
    def update_password(self, user_id: str, password_hash: str) -> None: ...
    def create_session(self, user_id: str, csrf_token: str) -> Any: ...
    def get_session(self, session_id: str) -> Any | None: ...
    def delete_session(self, session_id: str) -> None: ...
    def delete_user_sessions(self, user_id: str) -> None: ...
    def create_personal_workspace(self, user_id: str, email: str) -> Any: ...
    def membership_role(self, workspace_id: str, user_id: str) -> str | None: ...
    def list_workspaces(self, user_id: str) -> list[Any]: ...
    def create_project(self, workspace_id: str, created_by_user_id: str, title: str, description: str) -> Any: ...
    def get_project(self, project_id: str) -> Any | None: ...
    def list_projects(self, workspace_id: str) -> list[Any]: ...
    def count_user_projects(self, user_id: str) -> int: ...
    def update_project(self, project_id: str, title: str, description: str) -> Any: ...
    def delete_project(self, project_id: str) -> None: ...
    def create_review(self, workspace_id: str, project_id: str | None, data: dict[str, Any]) -> Any: ...
    def get_review(self, review_id: str) -> Any | None: ...
    def list_reviews(self, project_id: str) -> list[Any]: ...
    def add_source(self, data: dict[str, Any]) -> Any: ...
    def get_source(self, source_id: str) -> Any | None: ...
    def list_sources(self, review_id: str) -> list[Any]: ...
    def mark_source(self, source_id: str, state: str, metadata: dict[str, Any], warnings: list[str]) -> None: ...
    def add_chunks(self, source_id: str, workspace_id: str, chunks: list[dict[str, str]]) -> None: ...
    def search_evidence_chunks(
        self,
        workspace_id: str,
        review_id: str,
        query: str,
        limit: int,
    ) -> list[dict[str, object]]: ...
    def create_context_pack(self, workspace_id: str, data: dict[str, Any]) -> Any: ...
    def get_context_pack(self, context_pack_id: str) -> Any | None: ...
    def list_context_packs(self, workspace_id: str) -> list[Any]: ...
    def create_provider_connection(self, workspace_id: str, data: dict[str, Any]) -> Any: ...
    def get_provider_connection(self, connection_id: str) -> Any | None: ...
    def list_provider_connections(self, workspace_id: str) -> list[Any]: ...
    def create_model(self, workspace_id: str, data: dict[str, Any]) -> Any: ...
    def get_model(self, model_id: str) -> Any | None: ...
    def get_model_by_identifier(
        self,
        workspace_id: str,
        provider_connection_id: str,
        model_identifier: str,
    ) -> Any | None: ...
    def list_models(self, workspace_id: str) -> list[Any]: ...
    def update_model_probe(
        self,
        model_id: str,
        capabilities: list[str],
        provenance: str,
        verified: bool,
        probe_result: dict[str, Any],
    ) -> Any: ...
    def create_profile(self, workspace_id: str, data: dict[str, Any]) -> Any: ...
    def list_profiles(self, workspace_id: str) -> list[Any]: ...
    def create_run(
        self,
        workspace_id: str,
        review_id: str,
        routing_plan: dict[str, Any],
        created_by_user_id: str | None,
    ) -> Any: ...
    def count_user_workflows(self, user_id: str) -> int: ...
    def count_user_workflow_creations_since(self, user_id: str, since: datetime) -> int: ...
    def get_run(self, run_id: str) -> Any | None: ...
    def list_workflows(self, workspace_id: str) -> list[dict[str, Any]]: ...
    def update_run(self, run_id: str, state: str, usage: dict[str, Any] | None = None) -> None: ...
    def delete_run(self, run_id: str) -> None: ...
    def add_run_event(self, run_id: str, state: str, message: str) -> Any: ...
    def list_run_events(self, run_id: str) -> list[Any]: ...
    def create_report(self, workspace_id: str, run_id: str, data: dict[str, Any]) -> Any: ...
    def get_report_by_run(self, run_id: str) -> Any | None: ...
    def audit(
        self,
        workspace_id: str | None,
        actor_user_id: str | None,
        action: str,
        metadata: dict[str, Any],
    ) -> None: ...
    def commit(self) -> None: ...
